# Generated by Django 4.1.5 on 2023-01-05 16:27

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=512, verbose_name='Текст')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата змінення')),
            ],
            options={
                'verbose_name': 'Коммент',
                'verbose_name_plural': 'Комментарі',
            },
        ),
        migrations.CreateModel(
            name='PostImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=posts.models.user_directory_path_post_images)),
            ],
            options={
                'verbose_name': 'Зображеня',
                'verbose_name_plural': 'Зображеня',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Назва')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('deleted', models.BooleanField(default=False, verbose_name='Видалено')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата змінення')),
            ],
            options={
                'verbose_name': 'Публікація',
                'verbose_name_plural': 'Публікації',
            },
        ),
    ]
