# Generated by Django 4.1.3 on 2022-11-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Зображеня', 'verbose_name_plural': 'Зображеня'},
        ),
    ]
